# Generated by Django 5.0 on 2024-01-11 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('invoice_number', models.CharField(max_length=64, verbose_name='Invoice Number')),
                ('company_details', models.TextField(max_length=400, verbose_name='Company Details')),
                ('bill_to', models.TextField(max_length=400, verbose_name='Bill to')),
                ('company_logo', models.ImageField(upload_to='media/images')),
                ('discount', models.FloatField(default=0, verbose_name='Discount($)')),
                ('tax', models.FloatField(default=0, verbose_name='Tax % ')),
                ('shipping_fee', models.FloatField(default=0, verbose_name='Shipping Fee')),
                ('notes', models.TextField(max_length=300)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, verbose_name='Item Description')),
                ('unit_cost', models.FloatField(default=0, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoiceApp.invoice')),
            ],
        ),
    ]
