# Generated by Django 5.0 on 2024-01-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.FloatField(blank=True, default=0, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.FloatField(default=0, max_length=16),
        ),
    ]
