# Generated by Django 5.0 on 2024-01-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0002_item_total_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company_logo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
